default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: abdulahad
  password: hello246
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: event_management_platform_development

test:
  <<: *default
  database: event_management_platform_test

production:
  <<: *default
  database: event_management_platform_production
